#!/usr/bin/env bash
# Build container images with Cloud Build. Never with the local Docker daemon.
#
# Two independent reasons, both fatal to the local path:
#   * this workstation is arm64 and every target (Cloud Run Jobs, GKE Autopilot)
#     is amd64, so a locally built image either fails to start or silently runs
#     under emulation;
#   * the local Docker daemon on the reference machine is broken.
#
# Images are tagged with the immutable git SHA only. Promotion to a channel tag
# (:dev, :prod) is push-images.sh's job, so that "what is deployed" is always a
# digest that was actually built, and never a tag someone moved by hand.
#
# Usage: scripts/build-images.sh [TARGET...] [--tag SHA] [--create-repo] [--async]
#        TARGET defaults to every image the repo knows how to build.

set -euo pipefail
# shellcheck source-path=SCRIPTDIR
# shellcheck source=lib/common.sh
source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/lib/common.sh"

ALL_TARGETS=(agent-runtime-base agent-runtime-browser swarm-api swarm-scheduler swarm-quota-broker swarm-reconciler swarm-ui)
TARGETS=()
TAG=""
CREATE_REPO=0
ASYNC=0
DIGESTS_ONLY=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --tag)         TAG="$2"; shift 2 ;;
    --create-repo) CREATE_REPO=1; shift ;;
    --async)       ASYNC=1; shift ;;
    # Read digests back for a tag that is ALREADY built and write the manifest,
    # without rebuilding. Exists because the manifest can be lost while the
    # images are perfectly fine -- a session that expires mid-build loses every
    # digest read-back but not the six images Cloud Build already pushed. Before
    # this, recovering a lost manifest meant rebuilding everything to regenerate
    # a JSON file.
    --digests-only) DIGESTS_ONLY=1; shift ;;
    -h|--help)     sed -n '2,18p' "$0"; exit 0 ;;
    -*)            die "unknown flag: $1" ;;
    *)             TARGETS+=("$1"); shift ;;
  esac
done
[[ "${#TARGETS[@]}" -gt 0 ]] || TARGETS=("${ALL_TARGETS[@]}")

# NOTE: the only bash on the reference workstation is 3.2.57 (Apple ships no
# newer one). Empty arrays are therefore always expanded as ${arr[@]+"${arr[@]}"},
# because plain "${arr[@]}" on an empty array is an unbound-variable error under
# `set -u` in 3.2. No associative arrays, no mapfile, no ${var,,} anywhere.

require_cmd gcloud jq
TAG="${TAG:-$(git_sha)}"
CLOUDBUILD_REGION="${CLOUDBUILD_REGION:-${REGION}}"
BUILD_TIMEOUT="${BUILD_TIMEOUT:-3600s}"
BUILD_MACHINE="${BUILD_MACHINE:-E2_HIGHCPU_8}"

if git_dirty; then
  warn "working tree is dirty; ${TAG} will not reproduce from git alone"
fi

step "Artifact Registry"
# stderr captured rather than discarded: the failure that matters most here is
# an expired session, and discarding it turned that into "the repository does
# not exist. Run 'make infra' first" -- advice that cannot work, for a
# repository that was there all along.
REPO_ERR=""
if REPO_ERR="$(gcloud artifacts repositories describe "${ARTIFACT_REGISTRY}" \
     --project "${PROJECT_ID}" --location "${REGION}" --format='value(name)' 2>&1 >/dev/null)"; then
  ok "repository ${IMAGE_REPO}"
else
  # Exits here if the session is dead, so nothing below can misreport it.
  die_if_auth_failure "${REPO_ERR}"
  if [[ "${CREATE_REPO}" -eq 1 ]]; then
    info "creating Artifact Registry repository ${ARTIFACT_REGISTRY}"
    gcloud artifacts repositories create "${ARTIFACT_REGISTRY}" \
      --project "${PROJECT_ID}" --location "${REGION}" \
      --repository-format=docker \
      --description="Agent swarm images" \
      --labels="managed-by=swarm-bootstrap,component=images"
    ok "created ${IMAGE_REPO}"
  else
    err "Artifact Registry repository ${ARTIFACT_REGISTRY} does not exist in ${REGION}."
    [[ -z "${REPO_ERR}" ]] || printf '%s\n' "${REPO_ERR}" | head -n 2 | sed 's/^/     /' >&2
    die "run 'make infra' first, or re-run with --create-repo."
  fi
fi

# Find the build recipe for a target. Track B owns images/ and the service
# Dockerfiles, so both layouts are accepted rather than assumed.
find_recipe() {
  local target="$1" candidate
  for candidate in \
    "images/${target}/cloudbuild.yaml" \
    "apps/${target}/cloudbuild.yaml"; do
    if [[ -f "${REPO_ROOT}/${candidate}" ]]; then printf 'config\t%s' "${candidate}"; return 0; fi
  done
  for candidate in \
    "images/${target}/Dockerfile" \
    "apps/${target}/Dockerfile" \
    "docker/${target}/Dockerfile"; do
    if [[ -f "${REPO_ROOT}/${candidate}" ]]; then printf 'dockerfile\t%s' "${candidate}"; return 0; fi
  done
  return 1
}

# A Dockerfile with no cloudbuild.yaml gets a generated one. It is written to
# build/ and kept, so a failed build can be reproduced exactly.
generate_config() {
  local dockerfile="$1" image="$2" out="$3"
  cat >"${out}" <<YAML
# Generated by scripts/build-images.sh on $(iso_now). Do not edit; edit the
# Dockerfile or add a checked-in cloudbuild.yaml next to it instead.
timeout: ${BUILD_TIMEOUT}
options:
  machineType: ${BUILD_MACHINE}
  # CLOUD_LOGGING_ONLY keeps builds working when the legacy Cloud Build bucket
  # is absent and when a user-specified build service account is in use.
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --platform
      - linux/amd64
      - -f
      - ${dockerfile}
      - -t
      - ${image}:${TAG}
      - --build-arg
      - GIT_SHA=${TAG}
      - --build-arg
      - BUILD_TIME=$(iso_now)
      - .
images:
  - ${image}:${TAG}
YAML
}

SUBMIT_ARGS=(--project "${PROJECT_ID}" --region "${CLOUDBUILD_REGION}")
if [[ -n "${CLOUDBUILD_SERVICE_ACCOUNT:-}" ]]; then
  SUBMIT_ARGS+=(--service-account="projects/${PROJECT_ID}/serviceAccounts/${CLOUDBUILD_SERVICE_ACCOUNT}")
fi
[[ "${ASYNC}" -eq 1 ]] && SUBMIT_ARGS+=(--async)

MANIFEST="${BUILD_DIR}/images-${ENVIRONMENT}.json"
BUILT=()
SKIPPED=()

if [[ "${DIGESTS_ONLY}" -eq 1 ]]; then
  [[ -n "${TAG}" ]] || die "--digests-only needs an explicit --tag: it describes images that already exist, and the tag is the only thing that says which ones"
  info "reading back digests for ${TAG} without rebuilding"
  BUILT=("${TARGETS[@]}")
  # Emptied so the build loop below is skipped without restructuring it. Expanded
  # with the ${arr[@]+"${arr[@]}"} guard everywhere, because a plain "${arr[@]}"
  # on an empty array is an unbound-variable error under `set -u` in bash 3.2.
  TARGETS=()
fi

for target in ${TARGETS[@]+"${TARGETS[@]}"}; do
  step "Build ${target}"
  if ! recipe="$(find_recipe "${target}")"; then
    # FAIL, do not skip. A warning here let `make build` report success having
    # built nothing for swarm-api, swarm-scheduler and swarm-quota-broker, while
    # terraform/infra deployed those exact tags -- so the first sign of trouble
    # was Cloud Run reporting "Image not found" long after the build "passed".
    err "no Dockerfile or cloudbuild.yaml found for ${target}"
    dim "looked in images/${target}/, apps/${target}/, docker/${target}/"
    die "every target in ALL_TARGETS must be buildable; add a recipe or remove it from the list"
  fi
  kind="${recipe%%$'\t'*}"
  path="${recipe#*$'\t'}"
  image="${IMAGE_REPO}/${target}"

  config=""
  # Cloud Build REJECTS a substitution key the template never references, so the
  # two recipe kinds must be submitted differently:
  #   config      a checked-in cloudbuild.yaml, which parameterises itself with
  #               ${_IMAGE} / ${_TAG} / ${_DOCKERFILE} and needs them supplied
  #   dockerfile  a config generate_config() wrote, with every value already
  #               inlined -- passing substitutions here fails the submit with
  #               "key ... is not matched in the template"
  SUBS=()
  case "${kind}" in
    config)
      config="${REPO_ROOT}/${path}"
      # NOT _DOCKERFILE: for this kind `path` IS the cloudbuild.yaml, and passing
      # it made docker try to parse the YAML as a Dockerfile ("unknown
      # instruction: TIMEOUT:"). The config declares its own _DOCKERFILE default.
      SUBS=(--substitutions "_IMAGE=${image},_TAG=${TAG},_TARGET=${target}")
      info "using checked-in ${path}"
      ;;
    dockerfile)
      config="${BUILD_DIR}/cloudbuild-${target}.yaml"
      generate_config "${path}" "${image}" "${config}"
      info "generated $(basename "${config}") for ${path}"
      ;;
  esac

  info "submitting to Cloud Build (${CLOUDBUILD_REGION}), tag ${TAG}"
  gcloud builds submit "${REPO_ROOT}" \
    "${SUBMIT_ARGS[@]}" \
    --config "${config}" \
    ${SUBS[@]+"${SUBS[@]}"} \
    2>&1 | redact

  BUILT+=("${target}")
  ok "${image}:${TAG}"
done

if [[ "${ASYNC}" -eq 1 ]]; then
  hr
  ok "submitted ${#BUILT[@]} build(s) asynchronously; digests are recorded by the next non-async run"
  exit 0
fi

step "Digests"
# This loop USED TO discard stderr and `continue` on an empty digest, which cost
# a real deploy on 2026-09-18: the operator's gcloud session expired during a
# 15-minute build, all six read-backs failed identically, and the script warned
# six times, wrote a manifest with an EMPTY images array, printed
# "ok built 6 image(s)" and exited 0. push-images.sh and deploy.sh consume that
# manifest, so a successful build produced an artifact that promised six images
# and listed none.
#
# Two rules now, and the second matters as much as the first:
#   1. stderr is CAPTURED, so a dead session is named as a dead session --
#      die_if_auth_failure is used correctly 140 lines above this, for the
#      repository probe, and was simply never applied here;
#   2. a digest that cannot be read is FATAL. There is no useful partial
#      manifest: one built image missing from it is a service that silently
#      keeps its old revision on the next deploy.
DIGEST_OUT="$(mktemp "${TMPDIR:-/tmp}/swarm-digest.XXXXXX")"
trap 'rm -f "${DIGEST_OUT}"' EXIT INT TERM

entries='[]'
MISSING=()
for target in ${BUILT[@]+"${BUILT[@]}"}; do
  image="${IMAGE_REPO}/${target}"
  digest=""
  digest_err=""
  # stdout to a file, stderr into the substitution: a command substitution runs
  # in a subshell, so anything assigned inside one is lost to the caller.
  # `artifacts docker images describe` is NOT used here, though it is the
  # obvious command and was used until 2026-09-18. It returns vulnerability data
  # alongside the digest, so it calls Container Analysis and needs
  # `containeranalysis.occurrences.list` -- which the operator running a build
  # does not necessarily hold. The denial it produces names a permission that
  # has nothing to do with images, on a project id rendered as an opaque number,
  # and the old code turned that into "no digest could be read back".
  #
  # `tags list` answers the only question being asked -- which digest does this
  # tag point at -- from Artifact Registry alone.
  if digest_err="$(gcloud artifacts docker tags list "${image}" \
       --project "${PROJECT_ID}" --filter="tag:${TAG}" --format='value(version)' \
       2>&1 >"${DIGEST_OUT}")"; then
    digest="$(tr -d '[:space:]' <"${DIGEST_OUT}")"
  else
    # Exits here if the session is dead, so nothing below can misreport it as a
    # missing image.
    die_if_auth_failure "${digest_err}"
  fi
  if [[ -z "${digest}" ]]; then
    err "${target}: built, but its digest could not be read back"
    [[ -z "${digest_err}" ]] || printf '%s\n' "${digest_err}" | head -n 2 | sed 's/^/     /' >&2
    MISSING+=("${target}")
    continue
  fi
  printf '  %-22s %s\n' "${target}" "${digest}" >&2
  entries="$(jq -c --arg n "${target}" --arg i "${image}" --arg t "${TAG}" --arg d "${digest}" \
    '. + [{name:$n, image:$i, tag:$t, digest:$d, ref:($i + "@" + $d)}]' <<<"${entries}")"
done

if [[ "${#MISSING[@]}" -gt 0 ]]; then
  die "no manifest written: ${#MISSING[@]} of ${#BUILT[@]} image(s) built but unreadable (${MISSING[*]-}). The images may well exist; what is not true is that this run can describe them, and a manifest that omits them would deploy the previous revision of each without saying so."
fi

jq -n --arg tag "${TAG}" --arg at "$(iso_now)" --arg env "${ENVIRONMENT}" \
      --argjson images "${entries}" \
   '{tag:$tag, built_at:$at, environment:$env, images:$images}' >"${MANIFEST}"

hr
ok "built ${#BUILT[@]} image(s) at tag ${TAG}"
[[ "${#SKIPPED[@]}" -eq 0 ]] || warn "skipped (no recipe): ${SKIPPED[*]-}"
info "manifest: ${MANIFEST}"
