#!/usr/bin/env bash
# Build container images with Cloud Build. Never with the local Docker daemon.
#
# Two independent reasons, both fatal to the local path:
#   * this workstation is arm64 and every target (Cloud Run Jobs, GKE Autopilot)
#     is amd64, so a locally built image either fails to start or silently runs
#     under emulation;
#   * the local Docker daemon on the reference machine is broken.
#
# Images are tagged with the immutable git SHA only. Promotion to a channel tag
# (:dev, :prod) is push-images.sh's job, so that "what is deployed" is always a
# digest that was actually built, and never a tag someone moved by hand.
#
# Usage: scripts/build-images.sh [TARGET...] [--tag SHA] [--create-repo] [--async]
#        TARGET defaults to every image the repo knows how to build.

set -euo pipefail
# shellcheck source-path=SCRIPTDIR
# shellcheck source=lib/common.sh
source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/lib/common.sh"

ALL_TARGETS=(agent-runtime-base agent-runtime-browser swarm-api swarm-scheduler swarm-quota-broker swarm-reconciler)
TARGETS=()
TAG=""
CREATE_REPO=0
ASYNC=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --tag)         TAG="$2"; shift 2 ;;
    --create-repo) CREATE_REPO=1; shift ;;
    --async)       ASYNC=1; shift ;;
    -h|--help)     sed -n '2,18p' "$0"; exit 0 ;;
    -*)            die "unknown flag: $1" ;;
    *)             TARGETS+=("$1"); shift ;;
  esac
done
[[ "${#TARGETS[@]}" -gt 0 ]] || TARGETS=("${ALL_TARGETS[@]}")

# NOTE: the only bash on the reference workstation is 3.2.57 (Apple ships no
# newer one). Empty arrays are therefore always expanded as ${arr[@]+"${arr[@]}"},
# because plain "${arr[@]}" on an empty array is an unbound-variable error under
# `set -u` in 3.2. No associative arrays, no mapfile, no ${var,,} anywhere.

require_cmd gcloud jq
TAG="${TAG:-$(git_sha)}"
CLOUDBUILD_REGION="${CLOUDBUILD_REGION:-${REGION}}"
BUILD_TIMEOUT="${BUILD_TIMEOUT:-3600s}"
BUILD_MACHINE="${BUILD_MACHINE:-E2_HIGHCPU_8}"

if git_dirty; then
  warn "working tree is dirty; ${TAG} will not reproduce from git alone"
fi

step "Artifact Registry"
# stderr captured rather than discarded: the failure that matters most here is
# an expired session, and discarding it turned that into "the repository does
# not exist. Run 'make infra' first" -- advice that cannot work, for a
# repository that was there all along.
REPO_ERR=""
if REPO_ERR="$(gcloud artifacts repositories describe "${ARTIFACT_REGISTRY}" \
     --project "${PROJECT_ID}" --location "${REGION}" --format='value(name)' 2>&1 >/dev/null)"; then
  ok "repository ${IMAGE_REPO}"
else
  # Exits here if the session is dead, so nothing below can misreport it.
  die_if_auth_failure "${REPO_ERR}"
  if [[ "${CREATE_REPO}" -eq 1 ]]; then
    info "creating Artifact Registry repository ${ARTIFACT_REGISTRY}"
    gcloud artifacts repositories create "${ARTIFACT_REGISTRY}" \
      --project "${PROJECT_ID}" --location "${REGION}" \
      --repository-format=docker \
      --description="Agent swarm images" \
      --labels="managed-by=swarm-bootstrap,component=images"
    ok "created ${IMAGE_REPO}"
  else
    err "Artifact Registry repository ${ARTIFACT_REGISTRY} does not exist in ${REGION}."
    [[ -z "${REPO_ERR}" ]] || printf '%s\n' "${REPO_ERR}" | head -n 2 | sed 's/^/     /' >&2
    die "run 'make infra' first, or re-run with --create-repo."
  fi
fi

# Find the build recipe for a target. Track B owns images/ and the service
# Dockerfiles, so both layouts are accepted rather than assumed.
find_recipe() {
  local target="$1" candidate
  for candidate in \
    "images/${target}/cloudbuild.yaml" \
    "apps/${target}/cloudbuild.yaml"; do
    if [[ -f "${REPO_ROOT}/${candidate}" ]]; then printf 'config\t%s' "${candidate}"; return 0; fi
  done
  for candidate in \
    "images/${target}/Dockerfile" \
    "apps/${target}/Dockerfile" \
    "docker/${target}/Dockerfile"; do
    if [[ -f "${REPO_ROOT}/${candidate}" ]]; then printf 'dockerfile\t%s' "${candidate}"; return 0; fi
  done
  return 1
}

# A Dockerfile with no cloudbuild.yaml gets a generated one. It is written to
# build/ and kept, so a failed build can be reproduced exactly.
generate_config() {
  local dockerfile="$1" image="$2" out="$3"
  cat >"${out}" <<YAML
# Generated by scripts/build-images.sh on $(iso_now). Do not edit; edit the
# Dockerfile or add a checked-in cloudbuild.yaml next to it instead.
timeout: ${BUILD_TIMEOUT}
options:
  machineType: ${BUILD_MACHINE}
  # CLOUD_LOGGING_ONLY keeps builds working when the legacy Cloud Build bucket
  # is absent and when a user-specified build service account is in use.
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --platform
      - linux/amd64
      - -f
      - ${dockerfile}
      - -t
      - ${image}:${TAG}
      - --build-arg
      - GIT_SHA=${TAG}
      - --build-arg
      - BUILD_TIME=$(iso_now)
      - .
images:
  - ${image}:${TAG}
YAML
}

SUBMIT_ARGS=(--project "${PROJECT_ID}" --region "${CLOUDBUILD_REGION}")
if [[ -n "${CLOUDBUILD_SERVICE_ACCOUNT:-}" ]]; then
  SUBMIT_ARGS+=(--service-account="projects/${PROJECT_ID}/serviceAccounts/${CLOUDBUILD_SERVICE_ACCOUNT}")
fi
[[ "${ASYNC}" -eq 1 ]] && SUBMIT_ARGS+=(--async)

MANIFEST="${BUILD_DIR}/images-${ENVIRONMENT}.json"
BUILT=()
SKIPPED=()

for target in "${TARGETS[@]}"; do
  step "Build ${target}"
  if ! recipe="$(find_recipe "${target}")"; then
    # FAIL, do not skip. A warning here let `make build` report success having
    # built nothing for swarm-api, swarm-scheduler and swarm-quota-broker, while
    # terraform/infra deployed those exact tags -- so the first sign of trouble
    # was Cloud Run reporting "Image not found" long after the build "passed".
    err "no Dockerfile or cloudbuild.yaml found for ${target}"
    dim "looked in images/${target}/, apps/${target}/, docker/${target}/"
    die "every target in ALL_TARGETS must be buildable; add a recipe or remove it from the list"
  fi
  kind="${recipe%%$'\t'*}"
  path="${recipe#*$'\t'}"
  image="${IMAGE_REPO}/${target}"

  config=""
  # Cloud Build REJECTS a substitution key the template never references, so the
  # two recipe kinds must be submitted differently:
  #   config      a checked-in cloudbuild.yaml, which parameterises itself with
  #               ${_IMAGE} / ${_TAG} / ${_DOCKERFILE} and needs them supplied
  #   dockerfile  a config generate_config() wrote, with every value already
  #               inlined -- passing substitutions here fails the submit with
  #               "key ... is not matched in the template"
  SUBS=()
  case "${kind}" in
    config)
      config="${REPO_ROOT}/${path}"
      # NOT _DOCKERFILE: for this kind `path` IS the cloudbuild.yaml, and passing
      # it made docker try to parse the YAML as a Dockerfile ("unknown
      # instruction: TIMEOUT:"). The config declares its own _DOCKERFILE default.
      SUBS=(--substitutions "_IMAGE=${image},_TAG=${TAG},_TARGET=${target}")
      info "using checked-in ${path}"
      ;;
    dockerfile)
      config="${BUILD_DIR}/cloudbuild-${target}.yaml"
      generate_config "${path}" "${image}" "${config}"
      info "generated $(basename "${config}") for ${path}"
      ;;
  esac

  info "submitting to Cloud Build (${CLOUDBUILD_REGION}), tag ${TAG}"
  gcloud builds submit "${REPO_ROOT}" \
    "${SUBMIT_ARGS[@]}" \
    --config "${config}" \
    ${SUBS[@]+"${SUBS[@]}"} \
    2>&1 | redact

  BUILT+=("${target}")
  ok "${image}:${TAG}"
done

if [[ "${ASYNC}" -eq 1 ]]; then
  hr
  ok "submitted ${#BUILT[@]} build(s) asynchronously; digests are recorded by the next non-async run"
  exit 0
fi

step "Digests"
entries='[]'
for target in ${BUILT[@]+"${BUILT[@]}"}; do
  image="${IMAGE_REPO}/${target}"
  digest="$(gcloud artifacts docker images describe "${image}:${TAG}" \
    --project "${PROJECT_ID}" --format='value(image_summary.digest)' 2>/dev/null || true)"
  if [[ -z "${digest}" ]]; then
    warn "${target}: built, but no digest could be read back"
    continue
  fi
  printf '  %-22s %s\n' "${target}" "${digest}" >&2
  entries="$(jq -c --arg n "${target}" --arg i "${image}" --arg t "${TAG}" --arg d "${digest}" \
    '. + [{name:$n, image:$i, tag:$t, digest:$d, ref:($i + "@" + $d)}]' <<<"${entries}")"
done

jq -n --arg tag "${TAG}" --arg at "$(iso_now)" --arg env "${ENVIRONMENT}" \
      --argjson images "${entries}" \
   '{tag:$tag, built_at:$at, environment:$env, images:$images}' >"${MANIFEST}"

hr
ok "built ${#BUILT[@]} image(s) at tag ${TAG}"
[[ "${#SKIPPED[@]}" -eq 0 ]] || warn "skipped (no recipe): ${SKIPPED[*]-}"
info "manifest: ${MANIFEST}"
