#!/usr/bin/env bash
#
# The browser UX/UI suite: drive the real UI in a real browser and assert the
# things a person would otherwise have to eyeball.
#
# WHY THIS IS NOT PART OF `make test`
# -----------------------------------
# `make test` is offline, needs no credentials, creates nothing and finishes in
# seconds. That property is load-bearing -- it is the gate CLAUDE.md names
# before anyone may say a change is done, and it has to be cheap enough that
# nobody is tempted to skip it. This suite needs node, a built bundle and a
# headed Chromium, and takes minutes. Folding it in would make the cheap gate
# expensive and, the first time Chromium was missing on a machine, would teach
# somebody to add a skip guard -- which is how `tests/integration` rotted for 95
# commits. So it has its own target, `make ui-test`, and says so here.
#
# WHAT IT DRIVES, and why it is not "the deployed UI"
# ---------------------------------------------------
# There is no deployed UI. docs/web-ui/01-reachability.md is explicit: no load
# balancer was ever built, so no browser can reach swarm-api and nothing serves
# the bundle. The closest honest target is therefore the PRODUCTION bundle --
# `npm run build`, not the dev server, so the minified CSS and the real
# `import.meta.env.DEV === false` path are what gets audited -- served on the
# same origin as a /v1 control plane. That is exactly the topology the load
# balancer will present, and the app cannot tell the difference: it issues the
# same same-origin requests, and fetch.ts classifies real responses from a real
# socket.
#
# The control plane's bodies are generated by tests/browser/fixtures.py, which
# CALLS the real swarm_api serialisers rather than restating them. See the
# header of that file.
#
# Usage:
#   scripts/ui-test.sh                    # full matrix, headed
#   scripts/ui-test.sh --headless         # same, headless (CI, or no display)
#   scripts/ui-test.sh --only pools-pools # one view, for a quick loop
#   scripts/ui-test.sh --update-baseline  # record today's findings
#
# Exit codes:
#   0  no findings
#   1  findings, all of them already recorded in tests/browser/baseline.json
#   2  at least one NEW finding -- something got worse
#   3  the harness itself could not run (no browser, no bundle, no node)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib/common.sh
. "${SCRIPT_DIR}/lib/common.sh"

REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
UI_DIR="${REPO_ROOT}/apps/swarm-ui"
SUITE_DIR="${REPO_ROOT}/tests/browser"
OUT_DIR="${REPO_ROOT}/build/ui-test"
FIXTURES="${OUT_DIR}/fixtures.json"

# Resolved explicitly rather than taken off $PATH. CLAUDE.md records two tools
# on this machine where the wrong one wins $PATH and fails quietly; a node old
# enough to lack `node:fs/promises` would fail loudly, but a browse binary from
# somewhere unexpected would not.
NODE_BIN="$(prefer_local_bin node "${SWARM_NODE:-}")"
NPM_BIN="$(prefer_local_bin npm "${SWARM_NPM:-}")"
BROWSE_BIN="${SWARM_BROWSE_BIN:-${HOME}/.claude/skills/gstack/browse/dist/browse}"

RUNNER_ARGS=()
SKIP_BUILD=0
for arg in "$@"; do
  case "${arg}" in
    --skip-build) SKIP_BUILD=1 ;;
    *) RUNNER_ARGS+=("${arg}") ;;
  esac
done

step "browser UI suite"

[ -n "${NODE_BIN}" ] || die "node was not found. This suite needs node 20 or newer."
[ -n "${NPM_BIN}" ] || die "npm was not found."
[ -x "${BROWSE_BIN}" ] || die "the browse driver is not at ${BROWSE_BIN}. Set SWARM_BROWSE_BIN."
[ -d "${SUITE_DIR}" ] || die "${SUITE_DIR} is missing: the suite cannot run."

mkdir -p "${OUT_DIR}"

# --------------------------------------------------------------------------
# 1. The bundle. PRODUCTION, not the dev server.
# --------------------------------------------------------------------------
if [ "${SKIP_BUILD}" -eq 1 ]; then
  [ -f "${UI_DIR}/dist/index.html" ] || die "--skip-build was passed but ${UI_DIR}/dist holds no bundle."
  info "reusing the existing bundle in ${UI_DIR}/dist"
else
  if [ ! -d "${UI_DIR}/node_modules" ]; then
    info "installing swarm-ui dependencies"
    ( cd "${UI_DIR}" && "${NPM_BIN}" ci --no-audit --no-fund >/dev/null 2>&1 ) \
      || ( cd "${UI_DIR}" && "${NPM_BIN}" install --no-audit --no-fund >/dev/null )
  fi
  info "building the production bundle"
  ( cd "${UI_DIR}" && "${NPM_BIN}" run build >/dev/null )
fi
ok "bundle at ${UI_DIR}/dist"

# --------------------------------------------------------------------------
# 2. The control plane's bodies, through the real serialisers.
# --------------------------------------------------------------------------
# `uv run` rather than a bare python3: fixtures.py imports two FastAPI route
# handlers and calls them, which is what keeps /v1/runtimes and
# /v1/resource-classes from becoming a copy of the frozen catalogue.
#
# A COMMAND SUBSTITUTION IS A SUBSHELL, so the generator writes to a file and
# its status is read from the pipeline rather than from a variable it could
# never have set. That trap is in CLAUDE.md because it has already cost this
# repository a working check.
info "generating fixtures through swarm_api.codec"
if ! ( cd "${REPO_ROOT}" && uv run --project . python tests/browser/fixtures.py > "${FIXTURES}" ); then
  rm -f "${FIXTURES}"
  die "tests/browser/fixtures.py failed. The suite has no control plane to serve; it did NOT run."
fi
[ -s "${FIXTURES}" ] || die "tests/browser/fixtures.py produced an empty file."
ok "fixtures at ${FIXTURES}"

# --------------------------------------------------------------------------
# 3. The browser.
# --------------------------------------------------------------------------
# BROWSE_HEADED IS AN ENVIRONMENT VARIABLE, NEVER A --headed FLAG. The flag is
# folded into a config hash the daemon keeps; once set, every later call that
# does not repeat it reads as a different configuration and restarts the
# daemon, dropping the pinned tab in the middle of the matrix.
#
# ~/.gstack/browse.json is NOT touched here. buildRestartEnv reads mode:headed
# out of it to survive an autostart, and deleting it is how a run silently
# falls back to `launched` mode -- chromium.launch() plus newContext(), with no
# cookie jar at all.
export BROWSE_IDLE_TIMEOUT="${BROWSE_IDLE_TIMEOUT:-1800000}"
case " ${RUNNER_ARGS[*]+${RUNNER_ARGS[*]}} " in
  *" --headless "*) : ;;
  *) export BROWSE_HEADED=1 ;;
esac

# THE DAEMON IS NOT PROBED FOR READINESS HERE, deliberately.
#
# Three things make a precheck at this point actively misleading:
#   * a daemon in a bad state answers EVERY command with "No active page",
#     including `status` and `stop`, so a probe can report a healthy browser
#     that is not one;
#   * a cold start prints "Server failed to start within 8s" and is healthy a
#     second later, so a probe in the other direction gives up on a browser
#     that is fine;
#   * the obvious nudge does not work: `about:` is a blocked scheme in this
#     driver ("Only http:, https:, and file: URLs are permitted"), and the
#     first real URL there is to visit is the control plane, which is started
#     by the runner and does not exist yet.
#
# And a fourth: THIS SCRIPT MUST NOT TALK TO THE DAEMON AT ALL. Every `browse`
# invocation that cannot reach a daemon starts one, so a status check here and
# the runner's first call a second later are two processes racing to spawn the
# same server -- which is exactly what "Another instance is starting the
# server, waiting... Timed out waiting for another instance" means, and it left
# a half-started daemon that answered nothing for the rest of the run.
#
# So the whole conversation with the browser belongs to ONE process. The runner
# does the waiting, against the origin it is about to drive, and prints the
# mode it actually got into the report -- because a silent fall back from
# `headed` to `launched` loses the cookie jar and nothing else would say so.
:

# --------------------------------------------------------------------------
# 4. Run.
# --------------------------------------------------------------------------
step "driving the UI"
# The report is REMOVED first and its existence is checked afterwards.
#
# node exits 1 for a syntax error in a module, which is indistinguishable from
# this suite's "findings, none new" -- and that is exactly the shape this
# repository keeps producing: a failure wearing a success code. The artifact is
# the evidence the run happened, so a missing artifact is a harness failure no
# matter what the exit status says.
rm -f "${OUT_DIR}/report.txt"
set +e
SWARM_BROWSE_BIN="${BROWSE_BIN}" "${NODE_BIN}" "${SUITE_DIR}/runner.mjs" \
  --fixtures "${FIXTURES}" \
  --out "${OUT_DIR}" \
  ${RUNNER_ARGS[@]+"${RUNNER_ARGS[@]}"}
RESULT=$?
set -e

if [ ! -f "${OUT_DIR}/report.txt" ]; then
  hr
  err "the runner exited ${RESULT} and wrote no report, so the suite did NOT run."
  err "Treat this as a harness failure, never as a pass."
  exit 3
fi

hr
case "${RESULT}" in
  0) ok   "no findings" ;;
  1) warn "findings, all already recorded in tests/browser/baseline.json" ;;
  2) err  "NEW findings -- something got worse. See ${OUT_DIR}/report.txt" ;;
  *) err  "the suite did not complete (exit ${RESULT})" ;;
esac
log "report      ${OUT_DIR}/report.txt"
log "findings    ${OUT_DIR}/findings.json"
log "requests    ${OUT_DIR}/requests.json"
log "screenshots ${OUT_DIR}/screenshots/"
exit "${RESULT}"
