// A REAL `git diff --binary`, not a hand-written one. Produced by git 2.39.5
// with `git diff --cached --binary -C -C -M HEAD` over a scratch repository
// staged to hold one of every case the parser claims to read: an added file
// whose path has a space, a GIT binary patch, a copy and a rename (each with a
// similarity index), CRLF content inside an LF patch, a deleted file, a mode
// change with no hunks, `\ No newline at end of file` on both sides, two
// hunks in one file, and a C-quoted path holding a tab.
//
// Kept as one JSON string per line so the carriage returns and the tab git
// appends after a path with a space survive every editor and every
// whitespace check between here and CI.
export const REAL_GIT_DIFF: string =
  [
    "diff --git a/added file.txt b/added file.txt",
    "new file mode 100644",
    "index 0000000..5786b13",
    "--- /dev/null",
    "+++ b/added file.txt\t",
    "@@ -0,0 +1,2 @@",
    "+brand",
    "+new",
    "diff --git a/blob.bin b/blob.bin",
    "index f80e56fd87f78853d4a0f745e7d586ce40341e41..b367b393ae54bc3c0051465f243988b0cd6391cc 100644",
    "GIT binary patch",
    "literal 12",
    "TcmZQzWKzgWEmug&$xi|R4)g;p",
    "",
    "literal 12",
    "TcmZQzWKzh_Nl{43$xi|R4!Z*)",
    "",
    "diff --git a/copysrc.txt b/copied.txt",
    "similarity index 90%",
    "copy from copysrc.txt",
    "copy to copied.txt",
    "index a3fb829..e88c482 100644",
    "--- a/copysrc.txt",
    "+++ b/copied.txt",
    "@@ -4,3 +4,4 @@ gamma",
    " delta",
    " epsilon",
    " zeta",
    "+eta",
    "diff --git a/crlf.txt b/crlf.txt",
    "index a4b32e8..6a1f191 100644",
    "--- a/crlf.txt",
    "+++ b/crlf.txt",
    "@@ -1,2 +1,2 @@",
    " crlf one\r",
    "-crlf two\r",
    "+crlf TWO\r",
    "diff --git a/deleted.txt b/deleted.txt",
    "deleted file mode 100644",
    "index b8962c3..0000000",
    "--- a/deleted.txt",
    "+++ /dev/null",
    "@@ -1,2 +0,0 @@",
    "-gone",
    "-away",
    "diff --git a/old name.txt b/new name.txt",
    "similarity index 87%",
    "rename from old name.txt",
    "rename to new name.txt",
    "index b00a0f1..0383414 100644",
    "--- a/old name.txt\t",
    "+++ b/new name.txt\t",
    "@@ -2,7 +2,7 @@ one",
    " two",
    " three",
    " four",
    "-five",
    "+FIVE",
    " six",
    " seven",
    " eight",
    "diff --git a/nonl.txt b/nonl.txt",
    "index 20cbb4d..c808551 100644",
    "--- a/nonl.txt",
    "+++ b/nonl.txt",
    "@@ -1 +1,2 @@",
    "-no newline",
    "\\ No newline at end of file",
    "+no newline",
    "+now with more",
    "\\ No newline at end of file",
    "diff --git a/run.sh b/run.sh",
    "old mode 100644",
    "new mode 100755",
    "diff --git a/src.txt b/src.txt",
    "index f696b4b..a4b62e8 100644",
    "--- a/src.txt",
    "+++ b/src.txt",
    "@@ -1,5 +1,5 @@",
    " line1",
    "-line2",
    "+LINE TWO",
    " line3",
    " line4",
    " line5",
    "@@ -15,6 +15,6 @@ line14",
    " line15",
    " line16",
    " line17",
    "-line18",
    "+LINE EIGHTEEN",
    " line19",
    " line20",
    "diff --git \"a/tab\\there.txt\" \"b/tab\\there.txt\"",
    "index 8cc35a3..c1b0730 100644",
    "--- \"a/tab\\there.txt\"",
    "+++ \"b/tab\\there.txt\"",
    "@@ -1 +1 @@",
    "-tab",
    "+x",
    "\\ No newline at end of file",
  ].join('\n') + '\n'
